### PR TITLE
changed the bullet train logo on the sign in and sign up pages to ren…

### PR DESCRIPTION
**Pull request by gencalada**
…der the new LEARN logo

# Submitting Pull Request

### Ticket

ID number:

Branch name:

Description:

### Notes

Notes for the reviewer:

Contributors:

### CODE REVIEW

**Review by elysemontano — CHANGES_REQUESTED** [review]
Were there any sizing changes that need to be addressed?

**Comment by gencalada** [comment]
Yes, there were. We pulled up each of the original logo's sizing externally and using the LEARN logo as a template, we made three copies mimicing each of the original logos sizing.

**Comment by gencalada** [comment]
Only one logo, specifically the 'logo.png' is being used. The other two LEARN logos are not being used.

**Review by elysemontano — CHANGES_REQUESTED** [review]
Let's remove unused logos. I would also recommend not resizing the image asset, instead using the original and fitting in with styling. You may need the original size of that asset somewhere else in the future and we don't want duplicates.

**Review by elysemontano — CHANGES_REQUESTED** [review]
Double check if the acceptance criteria calls for the bullet train logo to be deleted, or just removed from the pages specifically.

**Comment by gencalada** [comment]
we have readded the image 🙌

**Review by elysemontano — APPROVED** [review]
I will approve, but something to consider looking into is how you would modify the view. This may require further research and provide more insight in how to do styling if need be in the future.

**Pull request merged**
